// Mart Korean — all learning content.
// Item schema: { ko, say, en, bis } + optional note (short English), casual ({ko,say,en,bis}),
// pack (romanization printed on packaging), listenOnly (lesson-level flag).
// Respelling rules: ㅏ ah / ㅓ uh / ㅗ oh / ㅜ oo / ㅡ eu / ㅣ ee / ㅐㅔ eh, syllables hyphenated,
// linked/assimilated sounds written as actually pronounced.

const APP_DATA = {
  meta: { title: 'Mart Korean', version: 1 },

  sounds: [
    { id: 'vowels', title: 'Easy vowels: ㅏ ㅗ ㅜ ㅣ ㅐ/ㅔ',
      tip_en: 'Korean vowels are pure sounds, same as Bisaya: ㅏ=ah, ㅗ=oh, ㅜ=oo, ㅣ=ee, ㅐ/ㅔ=eh.',
      tip_bis: 'Ang Korean vowels pareha ra sa Binisaya: a, o, u, i, e. Sayon ra ni!',
      examples: [
        { ko: '만두', say: 'mahn-doo', en: 'dumpling', bis: 'dumpling' },
        { ko: '우유', say: 'oo-yoo', en: 'milk', bis: 'gatas' },
      ] },
    { id: 'uh', title: 'ㅓ — the "uh" sound',
      tip_en: 'Like "u" in English "up". Relax your mouth. We always write it as "uh".',
      tip_bis: 'Pareha sa "u" sa English nga "up". Wala ni sa Binisaya, pero sayon ra.',
      examples: [
        { ko: '어서 오세요', say: 'uh-suh oh-seh-yo', en: 'Welcome!', bis: 'Dayon!' },
        { ko: '라면', say: 'rah-myun', en: 'ramyeon noodles', bis: 'ramyeon noodles' },
      ] },
    { id: 'eu', title: 'ㅡ — the "eu" sound',
      tip_en: 'Say "oo" but with flat lips, like you are smiling. We write it as "eu".',
      tip_bis: 'Isulti ang "u" pero i-flat ang ngabil, mura kag nag-smile.',
      examples: [
        { ko: '그거', say: 'geu-guh', en: 'that thing', bis: 'kana' },
        { ko: '들기름', say: 'deul-gee-reum', en: 'perilla oil', bis: 'lana sa perilla' },
      ] },
    { id: 'tense', title: 'ㄲ ㄸ ㅃ ㅆ ㅉ — strong sounds',
      tip_en: 'Say them hard and quick, with NO puff of air. Like holding your breath for a moment.',
      tip_bis: 'Kusgan ug paspas isulti, walay hangin nga mogawas sa baba.',
      examples: [
        { ko: '떡', say: 'ttuhk', en: 'rice cake', bis: 'rice cake' },
        { ko: '빼빼로', say: 'ppeh-ppeh-roh', en: 'Pepero snack', bis: 'Pepero snack' },
        { ko: '짜요', say: 'jjah-yo', en: 'it is salty', bis: 'parat' },
      ] },
    { id: 'jch', title: 'ㅈ / ㅊ — j and ch',
      tip_en: 'ㅈ = "j" as in jam. ㅊ = "ch" as in chair, with a puff of air.',
      tip_bis: 'ㅈ = "j" sa jam. ㅊ = "ch" sa chair, naay hangin.',
      examples: [
        { ko: '잔치국수', say: 'jahn-chee-gook-ssoo', en: 'banquet noodles', bis: 'noodles para sa okasyon' },
        { ko: '치약', say: 'chee-yahk', en: 'toothpaste', bis: 'toothpaste' },
      ] },
    { id: 'batchim', title: 'Final sounds (받침)',
      tip_en: 'Words can end in a closed sound: p, m, k, l, ng. Stop the sound — do not add a vowel after it.',
      tip_bis: 'Ang pulong mahimong matapos sa p, m, k, l, ng. Putla lang ang tingog, ayaw dugangi og vowel.',
      examples: [
        { ko: '밥', say: 'bahp', en: 'cooked rice', bis: 'kan-on' },
        { ko: '김', say: 'geem', en: 'seaweed sheet', bis: 'seaweed' },
        { ko: '물', say: 'mool', en: 'water', bis: 'tubig' },
      ] },
    { id: 'linking', title: 'Sounds flow together',
      tip_en: 'A final sound + a vowel link up: 있어요 sounds like "ee-ssuh-yo". Our guide always shows the REAL sound.',
      tip_bis: 'Ang mga tingog magdugtong. Ang guide kanunay magpakita sa tinuod nga paglitok.',
      examples: [
        { ko: '있어요', say: 'ee-ssuh-yo', en: 'there is / we have it', bis: 'naa' },
        { ko: '맛있어요', say: 'mah-shee-ssuh-yo', en: 'it is delicious', bis: 'lami' },
      ] },
  ],

  phraseGroups: [
    { id: 'mart', title: 'At the Mart', icon: '🏪', lessons: [
      { id: 'greeting', title: 'Greeting & Offering Help', icon: '🙋', items: [
        { ko: '어서 오세요', say: 'uh-suh oh-seh-yo', en: 'Welcome!', bis: 'Dayon!', note: 'Say this when a customer walks in' },
        { ko: '안녕하세요', say: 'ahn-nyuhng-hah-seh-yo', en: 'Hello', bis: 'Kumusta' },
        { ko: '찾으시는 거 있으세요?', say: 'chah-jeu-shee-neun guh ee-sseu-seh-yo?', en: 'Are you looking for something?', bis: 'Naa ba kay gipangita?' },
        { ko: '천천히 보세요', say: 'chun-chun-hee boh-seh-yo', en: 'Take your time', bis: 'Hinay-hinay lang og tan-aw' },
        { ko: '네, 손님', say: 'neh, sohn-neem', en: 'Yes, sir / ma\'am', bis: 'Oo, sir / ma\'am', note: '손님 = customer, a polite word' },
        { ko: '뭐 도와드릴까요?', say: 'mwuh doh-wah-deu-reel-kkah-yo?', en: 'How can I help you?', bis: 'Unsay akong ikatabang?' },
        { ko: '잠깐만요', say: 'jahm-kkahn-mahn-yo', en: 'Just a moment', bis: 'Kadiyot lang' },
        { ko: '새로 들어왔어요', say: 'seh-roh deu-ruh-wah-ssuh-yo', en: 'This just came in', bis: 'Bag-o ni nga abot', note: 'Good for recommending new stock' },
        { ko: '이거 세일이에요', say: 'ee-guh seh-ee-ree-eh-yo', en: 'This is on sale', bis: 'Naay sale ni' },
        { ko: '시식해 보세요', say: 'shee-shee-keh boh-seh-yo', en: 'Please try a sample', bis: 'Tilawi ni' },
        { ko: '천천히 말씀해 주세요', say: 'chun-chun-hee mahl-sseum-heh joo-seh-yo', en: 'Please speak slowly', bis: 'Hinaya lang og sulti palihug', note: 'Very useful while you are learning!' },
      ] },
      { id: 'customers', title: 'Understanding Customers', icon: '👂', listenOnly: true, items: [
        { ko: '라면 어디 있어요?', say: 'rah-myun uh-dee ee-ssuh-yo?', en: 'Where is the ramyeon?', bis: 'Asa ang ramyeon?' },
        { ko: '이거 얼마예요?', say: 'ee-guh uhl-mah-yeh-yo?', en: 'How much is this?', bis: 'Tagpila ni?' },
        { ko: '덜 매운 거 있어요?', say: 'duhl meh-oon guh ee-ssuh-yo?', en: 'Do you have a less spicy one?', bis: 'Naa bay dili kaayo halang?' },
        { ko: '이거 언제까지예요?', say: 'ee-guh uhn-jeh-kkah-jee-yeh-yo?', en: 'Until when is this good?', bis: 'Hangtod kanus-a ni?', note: 'Asking about expiry date' },
        { ko: '유통기한이 언제예요?', say: 'yoo-tohng-gee-hah-nee uhn-jeh-yeh-yo?', en: 'When is the expiry date?', bis: 'Kanus-a ang expiration?' },
        { ko: '봉투 하나 주세요', say: 'bohng-too hah-nah joo-seh-yo', en: 'One bag, please', bis: 'Usa ka bag palihug' },
        { ko: '이거 있어요?', say: 'ee-guh ee-ssuh-yo?', en: 'Do you have this?', bis: 'Naa mo ani?', note: 'Often shown with a photo on their phone' },
        { ko: '계산해 주세요', say: 'geh-sahn-heh joo-seh-yo', en: 'Check out, please', bis: 'Magbayad na ko' },
        { ko: '김치 어디 있어요?', say: 'geem-chee uh-dee ee-ssuh-yo?', en: 'Where is the kimchi?', bis: 'Asa ang kimchi?' },
        { ko: '더 큰 거 있어요?', say: 'duh keun guh ee-ssuh-yo?', en: 'Do you have a bigger one?', bis: 'Naa bay mas dako?' },
        { ko: '카드 돼요?', say: 'kah-deu dweh-yo?', en: 'Can I pay by card?', bis: 'Pwede ba mo-card?' },
        { ko: '소주 있어요?', say: 'soh-joo ee-ssuh-yo?', en: 'Do you have soju?', bis: 'Naa moy soju?' },
        { ko: '이거 어떻게 먹어요?', say: 'ee-guh uh-ttuh-keh muh-guh-yo?', en: 'How do you eat this?', bis: 'Unsaon ni pagkaon?' },
        { ko: '화장실 어디예요?', say: 'hwah-jahng-sheel uh-dee-yeh-yo?', en: 'Where is the restroom?', bis: 'Asa ang CR?' },
      ] },
      { id: 'directions', title: 'Directing & Locating', icon: '🧭', items: [
        { ko: '이쪽으로 오세요', say: 'ee-jjoh-geu-roh oh-seh-yo', en: 'Come this way', bis: 'Diri dapit' },
        { ko: '3번 통로에 있어요', say: 'sahm-bun tohng-noh-eh ee-ssuh-yo', en: 'It is in aisle 3', bis: 'Naa sa aisle 3' },
        { ko: '냉동 코너에 있어요', say: 'nehng-dohng koh-nuh-eh ee-ssuh-yo', en: 'It is in the frozen section', bis: 'Naa sa frozen section' },
        { ko: '저기 있어요', say: 'juh-gee ee-ssuh-yo', en: 'It is over there', bis: 'Tua didto' },
        { ko: '여기 있어요', say: 'yuh-gee ee-ssuh-yo', en: 'Here it is', bis: 'Ania ra' },
        { ko: '제가 안내해 드릴게요', say: 'jeh-gah ahn-neh-heh deu-reel-kkeh-yo', en: 'I will show you', bis: 'Ako ray mogiya nimo' },
        { ko: '맨 안쪽에 있어요', say: 'mehn ahn-jjoh-geh ee-ssuh-yo', en: 'It is at the very back', bis: 'Naa sa pinakasulod' },
        { ko: '입구 옆에 있어요', say: 'eep-kkoo yuh-peh ee-ssuh-yo', en: 'It is next to the entrance', bis: 'Naa tapad sa entrance' },
        { ko: '계산대 앞에 있어요', say: 'geh-sahn-deh ah-peh ee-ssuh-yo', en: 'It is in front of the cashier', bis: 'Naa atubangan sa cashier' },
        { ko: '위 칸에 있어요', say: 'wee kah-neh ee-ssuh-yo', en: 'It is on the top shelf', bis: 'Naa sa taas nga shelf' },
        { ko: '아래 칸에 있어요', say: 'ah-reh kah-neh ee-ssuh-yo', en: 'It is on the bottom shelf', bis: 'Naa sa ubos nga shelf' },
      ] },
      { id: 'checkout', title: 'Price & Checkout', icon: '💳', items: [
        { ko: '봉투 필요하세요?', say: 'bohng-too pee-ryo-hah-seh-yo?', en: 'Do you need a bag?', bis: 'Nagkinahanglan ka og bag?' },
        { ko: '카드 되세요', say: 'kah-deu dweh-seh-yo', en: 'We accept cards', bis: 'Pwede ang card' },
        { ko: '현금이요, 카드요?', say: 'hyun-geu-mee-yo, kah-deu-yo?', en: 'Cash or card?', bis: 'Cash o card?' },
        { ko: '영수증 드릴까요?', say: 'yuhng-soo-jeung deu-reel-kkah-yo?', en: 'Do you want a receipt?', bis: 'Gusto ka og resibo?' },
        { ko: '포인트 카드 있으세요?', say: 'poh-een-teu kah-deu ee-sseu-seh-yo?', en: 'Do you have a point card?', bis: 'Naa kay point card?' },
        { ko: '전부 오백 페소예요', say: 'juhn-boo oh-behk peh-soh-yeh-yo', en: 'It is 500 pesos in total', bis: '500 pesos tanan' },
        { ko: '여기 거스름돈이요', say: 'yuh-gee guh-seu-reum-doh-nee-yo', en: 'Here is your change', bis: 'Ania ang imong sukli' },
        { ko: '담아 드릴게요', say: 'dah-mah deu-reel-kkeh-yo', en: 'I will bag it for you', bis: 'Ako ray mosulod sa bag' },
        { ko: '결제됐습니다', say: 'gyul-jjeh-dwet-sseum-nee-dah', en: 'Payment is done', bis: 'Nabayran na' },
        { ko: '무거우니까 조심하세요', say: 'moo-guh-oo-nee-kkah joh-sheem-hah-seh-yo', en: 'It is heavy, be careful', bis: 'Bug-at ni, pag-amping' },
        { ko: '하나 더 사시면 할인돼요', say: 'hah-nah duh sah-shee-myun hah-reen-dweh-yo', en: 'Buy one more and get a discount', bis: 'Palit pa og usa, naay discount' },
      ] },
      { id: 'problems', title: 'Stock & Problems', icon: '🙏', items: [
        { ko: '죄송합니다, 품절이에요', say: 'jweh-sohng-hahm-nee-dah, poom-juh-ree-eh-yo', en: 'Sorry, it is sold out', bis: 'Pasayloa, nahurot na' },
        { ko: '내일 들어와요', say: 'neh-eel deu-ruh-wah-yo', en: 'It comes in tomorrow', bis: 'Moabot ugma' },
        { ko: '다음 주에 들어와요', say: 'dah-eum joo-eh deu-ruh-wah-yo', en: 'It comes in next week', bis: 'Moabot sunod semana' },
        { ko: '확인해 볼게요', say: 'hwah-geen-heh bohl-kkeh-yo', en: 'Let me check', bis: 'Akong susihon' },
        { ko: '잠시만 기다려 주세요', say: 'jahm-shee-mahn gee-dah-ryuh joo-seh-yo', en: 'Please wait a moment', bis: 'Palihug og hulat kadiyot' },
        { ko: '교환해 드릴게요', say: 'gyo-hwahn-heh deu-reel-kkeh-yo', en: 'I will exchange it for you', bis: 'Akong ilisan' },
        { ko: '환불해 드릴게요', say: 'hwahn-boo-reh deu-reel-kkeh-yo', en: 'I will give you a refund', bis: 'Akong i-refund' },
        { ko: '영수증 있으세요?', say: 'yuhng-soo-jeung ee-sseu-seh-yo?', en: 'Do you have the receipt?', bis: 'Naa kay resibo?' },
        { ko: '죄송합니다, 제 실수예요', say: 'jweh-sohng-hahm-nee-dah, jeh sheel-ssoo-yeh-yo', en: 'Sorry, my mistake', bis: 'Pasayloa, sayop nako' },
        { ko: '사장님께 물어볼게요', say: 'sah-jahng-neem-kkeh moo-ruh-bohl-kkeh-yo', en: 'I will ask the boss', bis: 'Pangutan-on nako ang boss' },
        { ko: '주문해 드릴까요?', say: 'joo-moon-heh deu-reel-kkah-yo?', en: 'Shall I order it for you?', bis: 'I-order nako para nimo?' },
      ] },
      { id: 'thanks', title: 'Small Talk & Thanks', icon: '💛', items: [
        { ko: '감사합니다, 또 오세요', say: 'gahm-sah-hahm-nee-dah, ttoh oh-seh-yo', en: 'Thank you, come again', bis: 'Salamat, balik ra mo' },
        { ko: '안녕히 가세요', say: 'ahn-nyuhng-hee gah-seh-yo', en: 'Goodbye', bis: 'Amping', note: 'Said to the person leaving' },
        { ko: '좋은 하루 되세요', say: 'joh-eun hah-roo dweh-seh-yo', en: 'Have a good day', bis: 'Maayong adlaw nimo' },
        { ko: '오랜만이에요', say: 'oh-rehn-mah-nee-eh-yo', en: 'Long time no see', bis: 'Dugay na ta wala nagkita' },
        { ko: '맛있게 드세요', say: 'mah-sheet-kkeh deu-seh-yo', en: 'Enjoy your food', bis: 'Maayong pagkaon' },
        { ko: '조심히 가세요', say: 'joh-sheem-hee gah-seh-yo', en: 'Get home safely', bis: 'Pag-amping sa dalan' },
        { ko: '또 뵐게요', say: 'ttoh bwehl-kkeh-yo', en: 'See you again', bis: 'Magkita ra ta usab' },
        { ko: '새해 복 많이 받으세요', say: 'seh-heh bohk mah-nee bah-deu-seh-yo', en: 'Happy New Year', bis: 'Malipayong Bag-ong Tuig' },
      ] },
      { id: 'numbers', title: 'Numbers for the Shop', icon: '🔢', items: [
        { ko: '하나, 둘, 셋', say: 'hah-nah, dool, seht', en: 'one, two, three (counting)', bis: 'usa, duha, tulo' },
        { ko: '넷, 다섯, 여섯', say: 'neht, dah-suht, yuh-suht', en: 'four, five, six', bis: 'upat, lima, unom' },
        { ko: '일곱, 여덟, 아홉, 열', say: 'eel-gohp, yuh-duhl, ah-hohp, yuhl', en: 'seven, eight, nine, ten', bis: 'pito, walo, siyam, napulo' },
        { ko: '한 개', say: 'hahn geh', en: 'one piece', bis: 'usa ka buok' },
        { ko: '두 개', say: 'doo geh', en: 'two pieces', bis: 'duha ka buok' },
        { ko: '세 개 주세요', say: 'seh geh joo-seh-yo', en: 'Three please (a customer says this)', bis: 'Tulo ka buok palihug' },
        { ko: '일, 이, 삼, 사, 오', say: 'eel, ee, sahm, sah, oh', en: '1 2 3 4 5 (for prices)', bis: '1 2 3 4 5 (para sa presyo)' },
        { ko: '육, 칠, 팔, 구, 십', say: 'yook, cheel, pahl, goo, sheep', en: '6 7 8 9 10 (for prices)', bis: '6 7 8 9 10 (para sa presyo)' },
        { ko: '백', say: 'behk', en: 'hundred (100)', bis: 'usa ka gatos' },
        { ko: '천', say: 'chun', en: 'thousand (1,000)', bis: 'usa ka libo' },
        { ko: '만', say: 'mahn', en: 'ten thousand (10,000)', bis: 'napulo ka libo' },
        { ko: '삼백 페소예요', say: 'sahm-behk peh-soh-yeh-yo', en: 'It is 300 pesos', bis: '300 pesos ni' },
      ] },
    ] },
    { id: 'daily', title: 'Daily Life', icon: '☀️', lessons: [
      { id: 'intro', title: 'Greetings & Introductions', icon: '👋', items: [
        { ko: '안녕하세요', say: 'ahn-nyuhng-hah-seh-yo', en: 'Hello', bis: 'Kumusta' },
        { ko: '저는 마리아예요', say: 'juh-neun mah-ree-ah-yeh-yo', en: 'I am Maria', bis: 'Ako si Maria', note: 'Put your own name before -yeh-yo' },
        { ko: '이름이 뭐예요?', say: 'ee-reu-mee mwuh-yeh-yo?', en: 'What is your name?', bis: 'Unsay imong pangalan?' },
        { ko: '반가워요', say: 'bahn-gah-wuh-yo', en: 'Nice to meet you', bis: 'Nalipay ko nga nagkaila ta',
          casual: { ko: '반가워', say: 'bahn-gah-wuh', en: 'Nice to meet you (casual)', bis: 'Nalipay ko (sa amigo)' } },
        { ko: '잘 지냈어요?', say: 'jahl jee-neh-ssuh-yo?', en: 'How have you been?', bis: 'Kumusta na ka?',
          casual: { ko: '잘 지냈어?', say: 'jahl jee-neh-ssuh?', en: 'How have you been? (casual)', bis: 'Kumusta na? (sa amigo)' } },
        { ko: '저는 필리핀 사람이에요', say: 'juh-neun peel-ree-peen sah-rah-mee-eh-yo', en: 'I am Filipino', bis: 'Pilipino ko' },
        { ko: '한국어 조금 해요', say: 'hahn-goo-guh joh-geum heh-yo', en: 'I speak a little Korean', bis: 'Gamay ra kong kabalo og Korean' },
        { ko: '만나서 반갑습니다', say: 'mahn-nah-suh bahn-gahp-sseum-nee-dah', en: 'Pleased to meet you (formal)', bis: 'Nalipay ko nga nagkita ta (pormal)' },
        { ko: '잘 부탁드립니다', say: 'jahl boo-tahk-deu-reem-nee-dah', en: 'Please take care of me', bis: 'Palihug ko ninyo og giya', note: 'Said when meeting someone you will work with' },
        { ko: '어디에서 왔어요?', say: 'uh-dee-eh-suh wah-ssuh-yo?', en: 'Where are you from?', bis: 'Taga-asa ka?' },
        { ko: '세부에서 왔어요', say: 'seh-boo-eh-suh wah-ssuh-yo', en: 'I am from Cebu', bis: 'Taga-Cebu ko' },
        { ko: '몇 살이에요?', say: 'myuht sah-ree-eh-yo?', en: 'How old are you?', bis: 'Pila imong edad?' },
      ] },
      { id: 'qa', title: 'Basic Questions & Answers', icon: '❓', items: [
        { ko: '이게 뭐예요?', say: 'ee-geh mwuh-yeh-yo?', en: 'What is this?', bis: 'Unsa ni?' },
        { ko: '어디예요?', say: 'uh-dee-yeh-yo?', en: 'Where is it?', bis: 'Asa man?' },
        { ko: '네', say: 'neh', en: 'Yes', bis: 'Oo' },
        { ko: '아니요', say: 'ah-nee-yo', en: 'No', bis: 'Dili' },
        { ko: '몰라요', say: 'mohl-lah-yo', en: 'I do not know', bis: 'Wala ko kabalo' },
        { ko: '알겠어요', say: 'ahl-geh-ssuh-yo', en: 'Got it / OK', bis: 'Sige, nasabtan nako' },
        { ko: '다시 말해 주세요', say: 'dah-shee mahl-heh joo-seh-yo', en: 'Please say it again', bis: 'Balika palihug' },
        { ko: '천천히 말해 주세요', say: 'chun-chun-hee mahl-heh joo-seh-yo', en: 'Please speak slowly', bis: 'Hinaya lang og sulti' },
        { ko: '뭐라고요?', say: 'mwuh-rah-goh-yo?', en: 'What did you say?', bis: 'Unsa to?' },
        { ko: '이해했어요', say: 'ee-heh-heh-ssuh-yo', en: 'I understand', bis: 'Nasabtan nako' },
        { ko: '이해 못 했어요', say: 'ee-heh moht heh-ssuh-yo', en: 'I did not understand', bis: 'Wala nako masabti' },
        { ko: '영어로 해도 돼요?', say: 'yuhng-uh-roh heh-doh dweh-yo?', en: 'Can I say it in English?', bis: 'Pwede ba sa English?' },
      ] },
      { id: 'feelings', title: 'Feelings & Reactions', icon: '😊', items: [
        { ko: '좋아요', say: 'joh-ah-yo', en: 'It is good / I like it', bis: 'Nindot / Ganahan ko',
          casual: { ko: '좋아', say: 'joh-ah', en: 'Good! (casual)', bis: 'Nindot! (sa amigo)' } },
        { ko: '진짜요?', say: 'jeen-jjah-yo?', en: 'Really?', bis: 'Tinuod?',
          casual: { ko: '진짜?', say: 'jeen-jjah?', en: 'Really? (casual)', bis: 'Tinuod? (sa amigo)' } },
        { ko: '대박', say: 'deh-bahk', en: 'Awesome! / No way!', bis: 'Grabe!' },
        { ko: '피곤해요', say: 'pee-gohn-heh-yo', en: 'I am tired', bis: 'Kapoy kaayo ko' },
        { ko: '배고파요', say: 'beh-goh-pah-yo', en: 'I am hungry', bis: 'Gigutom ko',
          casual: { ko: '배고파', say: 'beh-goh-pah', en: 'I am hungry (casual)', bis: 'Gutom na ko (sa amigo)' } },
        { ko: '괜찮아요', say: 'gwehn-chah-nah-yo', en: 'It is OK / I am fine', bis: 'Okay ra',
          casual: { ko: '괜찮아', say: 'gwehn-chah-nah', en: 'It is OK (casual)', bis: 'Okay ra (sa amigo)' } },
        { ko: '재미있어요', say: 'jeh-mee-ee-ssuh-yo', en: 'It is fun', bis: 'Lingaw kaayo' },
        { ko: '힘들어요', say: 'heem-deu-ruh-yo', en: 'It is hard / tough', bis: 'Lisod kaayo' },
        { ko: '행복해요', say: 'hehng-boh-keh-yo', en: 'I am happy', bis: 'Malipayon ko' },
        { ko: '졸려요', say: 'johl-lyuh-yo', en: 'I am sleepy', bis: 'Katulgon ko' },
        { ko: '심심해요', say: 'sheem-sheem-heh-yo', en: 'I am bored', bis: 'Laay kaayo' },
        { ko: '걱정하지 마세요', say: 'guhk-jjuhng-hah-jee mah-seh-yo', en: 'Do not worry', bis: 'Ayaw kabalaka' },
      ] },
      { id: 'food', title: 'Food & Eating Together', icon: '🍜', items: [
        { ko: '같이 먹어요', say: 'gah-chee muh-guh-yo', en: 'Let us eat together', bis: 'Mangaon ta' },
        { ko: '잘 먹겠습니다', say: 'jahl muhk-kkeht-sseum-nee-dah', en: 'Thanks for the food (before eating)', bis: 'Salamat sa pagkaon (sa dili pa mokaon)' },
        { ko: '맛있어요', say: 'mah-shee-ssuh-yo', en: 'It is delicious', bis: 'Lami kaayo!',
          casual: { ko: '맛있어', say: 'mah-shee-ssuh', en: 'Delicious! (casual)', bis: 'Lami! (sa amigo)' } },
        { ko: '매워요', say: 'meh-wuh-yo', en: 'It is spicy', bis: 'Halang' },
        { ko: '안 매워요', say: 'ahn meh-wuh-yo', en: 'It is not spicy', bis: 'Dili halang' },
        { ko: '배불러요', say: 'beh-bool-luh-yo', en: 'I am full', bis: 'Busog na kaayo ko' },
        { ko: '뭐 먹을래요?', say: 'mwuh muh-geul-leh-yo?', en: 'What do you want to eat?', bis: 'Unsay gusto nimong kaonon?' },
        { ko: '물 주세요', say: 'mool joo-seh-yo', en: 'Water, please', bis: 'Tubig palihug' },
        { ko: '잘 먹었습니다', say: 'jahl muh-guht-sseum-nee-dah', en: 'That was good (after eating)', bis: 'Salamat sa pagkaon (human mokaon)' },
        { ko: '달아요', say: 'dah-rah-yo', en: 'It is sweet', bis: 'Tam-is' },
        { ko: '짜요', say: 'jjah-yo', en: 'It is salty', bis: 'Parat' },
        { ko: '하나 더 주세요', say: 'hah-nah duh joo-seh-yo', en: 'One more, please', bis: 'Usa pa palihug' },
      ] },
      { id: 'plans', title: 'Making Plans & Time', icon: '📅', items: [
        { ko: '내일 만나요', say: 'neh-eel mahn-nah-yo', en: 'See you tomorrow', bis: 'Magkita ta ugma',
          casual: { ko: '내일 봐', say: 'neh-eel bwah', en: 'See you tomorrow (casual)', bis: 'Kita ta ugma (sa amigo)' } },
        { ko: '몇 시에요?', say: 'myuht shee-eh-yo?', en: 'What time?', bis: 'Unsang orasa?' },
        { ko: '주말에 뭐 해요?', say: 'joo-mah-reh mwuh heh-yo?', en: 'What are you doing this weekend?', bis: 'Unsay imong buhaton sa weekend?' },
        { ko: '시간 있어요?', say: 'shee-gahn ee-ssuh-yo?', en: 'Do you have time?', bis: 'Naa kay oras?' },
        { ko: '연락할게요', say: 'yuhl-lah-kahl-kkeh-yo', en: 'I will contact you', bis: 'Kontakon tika' },
        { ko: '좋아요, 그때 봐요', say: 'joh-ah-yo, geu-tteh bwah-yo', en: 'OK, see you then', bis: 'Sige, magkita ta unya' },
        { ko: '오늘 바빠요', say: 'oh-neul bah-ppah-yo', en: 'I am busy today', bis: 'Busy ko karon' },
        { ko: '늦어서 미안해요', say: 'neu-juh-suh mee-ahn-heh-yo', en: 'Sorry I am late', bis: 'Pasayloa, naulahi ko',
          casual: { ko: '미안해', say: 'mee-ahn-heh', en: 'Sorry (casual)', bis: 'Sorry (sa amigo)' } },
        { ko: '어디에서 만날까요?', say: 'uh-dee-eh-suh mahn-nahl-kkah-yo?', en: 'Where shall we meet?', bis: 'Asa ta magkita?' },
        { ko: '일 끝나고 봐요', say: 'eel kkeun-nah-goh bwah-yo', en: 'See you after work', bis: 'Magkita ta human sa trabaho' },
        { ko: '다음에 같이 가요', say: 'dah-eu-meh gah-chee gah-yo', en: 'Let us go together next time', bis: 'Kuyog ta sunod' },
        { ko: '잘 자요', say: 'jahl jah-yo', en: 'Good night', bis: 'Maayong gabii',
          casual: { ko: '잘 자', say: 'jahl jah', en: 'Good night (casual)', bis: 'Good night (sa amigo)' } },
      ] },
    ] },
  ],

  products: [
    { id: 'ramyeon', title: 'Ramyeon & Noodles', icon: '🍜', items: [
      { ko: '신라면', pack: 'Shin Ramyun', say: 'sheen-rah-myun', en: 'spicy instant noodles (the classic)', bis: 'halang nga instant noodles', note: 'Customers ask: 신라면 어디 있어요?' },
      { ko: '진라면', pack: 'Jin Ramen', say: 'jeen-rah-myun', en: 'instant noodles, mild or spicy', bis: 'instant noodles, mild o spicy' },
      { ko: '불닭볶음면', pack: 'Buldak', say: 'bool-dahk-boh-kkeum-myun', en: 'very spicy fire chicken noodles', bis: 'grabe ka halang nga noodles' },
      { ko: '짜파게티', pack: 'Chapagetti', say: 'jjah-pah-geh-tee', en: 'black bean sauce noodles', bis: 'noodles nga naay black bean sauce' },
      { ko: '너구리', pack: 'Neoguri', say: 'nuh-goo-ree', en: 'thick seafood noodles', bis: 'baga nga seafood noodles' },
      { ko: '비빔면', pack: 'Bibim Myun', say: 'bee-beem-myun', en: 'cold spicy mixed noodles', bis: 'bugnaw nga halang noodles' },
      { ko: '육개장 사발면', pack: 'Yukgaejang Bowl', say: 'yook-kkeh-jahng sah-bahl-myun', en: 'spicy beef cup noodles', bis: 'cup noodles nga baka, halang' },
      { ko: '우동', pack: 'Udon', say: 'oo-dohng', en: 'thick wheat noodles', bis: 'baga nga noodles' },
      { ko: '냉면', pack: 'Naengmyeon', say: 'nehng-myun', en: 'cold buckwheat noodles', bis: 'bugnaw nga noodles' },
      { ko: '당면', pack: 'Dangmyeon', say: 'dahng-myun', en: 'glass noodles for japchae', bis: 'sotanghon para sa japchae' },
      { ko: '잔치국수', pack: 'Janchi Guksu', say: 'jahn-chee-gook-ssoo', en: 'thin wheat noodles', bis: 'nipis nga noodles' },
    ] },
    { id: 'sauces', title: 'Pastes & Sauces', icon: '🥫', items: [
      { ko: '고추장', pack: 'Gochujang', say: 'goh-choo-jahng', en: 'spicy red pepper paste', bis: 'halang nga sarsa sa sili', note: 'Customers ask: 고추장 어디 있어요?' },
      { ko: '된장', pack: 'Doenjang', say: 'dwehn-jahng', en: 'soybean paste for soup', bis: 'soybean paste para sa sabaw' },
      { ko: '쌈장', pack: 'Ssamjang', say: 'ssahm-jahng', en: 'dipping paste for wraps and meat', bis: 'sawsawan para sa karne' },
      { ko: '간장', pack: 'Ganjang', say: 'gahn-jahng', en: 'soy sauce', bis: 'toyo' },
      { ko: '참기름', pack: 'Chamgireum', say: 'chahm-gee-reum', en: 'sesame oil', bis: 'lana sa linga' },
      { ko: '들기름', pack: 'Deulgireum', say: 'deul-gee-reum', en: 'perilla seed oil', bis: 'lana sa perilla' },
      { ko: '고춧가루', pack: 'Gochugaru', say: 'goh-choot-kkah-roo', en: 'red pepper powder', bis: 'pulbos sa sili' },
      { ko: '식초', pack: 'Sikcho', say: 'sheek-choh', en: 'vinegar', bis: 'suka' },
      { ko: '물엿', pack: 'Mulyeot', say: 'mool-lyuht', en: 'corn syrup for cooking', bis: 'syrup para sa pagluto' },
      { ko: '맛술', pack: 'Matsul', say: 'maht-ssool', en: 'cooking wine', bis: 'cooking wine' },
      { ko: '액젓', pack: 'Aekjeot', say: 'ehk-jjuht', en: 'fish sauce', bis: 'patis' },
    ] },
    { id: 'kimchi', title: 'Kimchi & Side Dishes', icon: '🥬', items: [
      { ko: '배추김치', pack: 'Baechu Kimchi', say: 'beh-choo-geem-chee', en: 'napa cabbage kimchi (the main one)', bis: 'kimchi nga repolyo', note: 'Customers ask: 김치 어디 있어요?' },
      { ko: '깍두기', pack: 'Kkakdugi', say: 'kkahk-ttoo-gee', en: 'cubed radish kimchi', bis: 'kimchi nga rabanos, kwadrado' },
      { ko: '총각김치', pack: 'Chonggak Kimchi', say: 'chohng-gahk-geem-chee', en: 'whole small radish kimchi', bis: 'kimchi nga gagmay nga rabanos' },
      { ko: '열무김치', pack: 'Yeolmu Kimchi', say: 'yuhl-moo-geem-chee', en: 'young radish leaf kimchi', bis: 'kimchi nga dahon sa rabanos' },
      { ko: '단무지', pack: 'Danmuji', say: 'dahn-moo-jee', en: 'yellow pickled radish', bis: 'dilaw nga atsara nga rabanos' },
      { ko: '장아찌', pack: 'Jangajji', say: 'jahng-ah-jjee', en: 'pickled vegetables', bis: 'atsara nga utanon' },
      { ko: '젓갈', pack: 'Jeotgal', say: 'juht-kkahl', en: 'salted fermented seafood', bis: 'ginamos' },
      { ko: '김', pack: 'Gim', say: 'geem', en: 'roasted seaweed sheets', bis: 'seaweed nga sinanag' },
      { ko: '미역', pack: 'Miyeok', say: 'mee-yuhk', en: 'dried seaweed for soup', bis: 'uga nga seaweed para sa sabaw' },
      { ko: '멸치', pack: 'Myeolchi', say: 'myuhl-chee', en: 'dried anchovies', bis: 'uga nga bolinaw' },
      { ko: '콩나물', pack: 'Kongnamul', say: 'kohng-nah-mool', en: 'soybean sprouts', bis: 'togue' },
    ] },
    { id: 'frozen', title: 'Frozen Food', icon: '🧊', items: [
      { ko: '만두', pack: 'Mandu', say: 'mahn-doo', en: 'Korean dumplings', bis: 'dumplings nga Korean', note: 'Customers ask: 만두 어디 있어요?' },
      { ko: '김치만두', pack: 'Kimchi Mandu', say: 'geem-chee-mahn-doo', en: 'kimchi dumplings', bis: 'dumplings nga naay kimchi' },
      { ko: '떡', pack: 'Tteok', say: 'ttuhk', en: 'rice cake', bis: 'rice cake' },
      { ko: '떡볶이 떡', pack: 'Tteokbokki Tteok', say: 'ttuhk-ppoh-kkee ttuhk', en: 'rice cake sticks for tteokbokki', bis: 'rice cake para sa tteokbokki' },
      { ko: '어묵', pack: 'Eomuk', say: 'uh-mook', en: 'fish cake', bis: 'fish cake' },
      { ko: '핫도그', pack: 'Korean Corn Dog', say: 'haht-ttoh-geu', en: 'Korean corn dog', bis: 'Korean corn dog' },
      { ko: '붕어빵', pack: 'Bungeoppang', say: 'boong-uh-ppahng', en: 'fish-shaped bread with red bean', bis: 'pan nga porma og isda, naay red bean' },
      { ko: '호떡', pack: 'Hotteok', say: 'hoh-ttuhk', en: 'sweet filled pancake', bis: 'tam-is nga pancake' },
      { ko: '만두피', pack: 'Mandu Wrappers', say: 'mahn-doo-pee', en: 'dumpling wrappers', bis: 'wrapper sa dumplings' },
      { ko: '냉동 삼겹살', pack: 'Samgyeopsal', say: 'nehng-dohng sahm-gyup-ssahl', en: 'frozen pork belly', bis: 'frozen nga liempo' },
      { ko: '순대', pack: 'Sundae', say: 'soon-deh', en: 'Korean blood sausage', bis: 'Korean nga dinuguan sausage' },
    ] },
    { id: 'snacks', title: 'Snacks & Sweets', icon: '🍪', items: [
      { ko: '새우깡', pack: 'Saewookkang', say: 'seh-oo-kkahng', en: 'shrimp chips', bis: 'chips nga pasayan', note: 'Customers ask: 과자 어디 있어요? (Where are the snacks?)' },
      { ko: '초코파이', pack: 'Choco Pie', say: 'choh-koh-pah-ee', en: 'chocolate marshmallow pie', bis: 'chocolate pie nga naay marshmallow' },
      { ko: '빼빼로', pack: 'Pepero', say: 'ppeh-ppeh-roh', en: 'chocolate stick biscuits', bis: 'biscuit sticks nga naay chocolate' },
      { ko: '홈런볼', pack: 'Home Run Ball', say: 'hohm-nuhn-bohl', en: 'puff pastry balls with chocolate', bis: 'gagmay nga pastry balls' },
      { ko: '약과', pack: 'Yakgwa', say: 'yahk-kkwah', en: 'traditional honey cookie', bis: 'tradisyonal nga cookie nga naay dugos' },
      { ko: '뻥튀기', pack: 'Ppeongtwigi', say: 'ppuhng-twee-gee', en: 'puffed rice snack', bis: 'ampaw' },
      { ko: '바나나킥', pack: 'Banana Kick', say: 'bah-nah-nah-keek', en: 'banana flavored puff snack', bis: 'snack nga lami og saging' },
      { ko: '꼬북칩', pack: 'Kkobuk Chip', say: 'kkoh-book-cheep', en: 'layered corn chips', bis: 'corn chips nga naay layers' },
      { ko: '마이쮸', pack: 'My Chew', say: 'mah-ee-jjyoo', en: 'soft fruit chewy candy', bis: 'chewy candy nga prutas' },
      { ko: '젤리', pack: 'Jelly', say: 'jehl-lee', en: 'jelly candy', bis: 'jelly candy' },
      { ko: '유과', pack: 'Yugwa', say: 'yoo-gwah', en: 'traditional crispy rice snack', bis: 'tradisyonal nga snack nga bugas' },
    ] },
    { id: 'drinks', title: 'Drinks & Alcohol', icon: '🍶', items: [
      { ko: '소주', pack: 'Soju', say: 'soh-joo', en: 'Korean distilled alcohol', bis: 'Korean nga ilimnon, isog', note: 'Customers ask: 소주 있어요?' },
      { ko: '막걸리', pack: 'Makgeolli', say: 'mahk-kkuhl-lee', en: 'milky rice wine', bis: 'puti nga rice wine' },
      { ko: '맥주', pack: 'Maekju', say: 'mehk-jjoo', en: 'beer', bis: 'beer' },
      { ko: '식혜', pack: 'Sikhye', say: 'shee-kkyeh', en: 'sweet rice drink', bis: 'tam-is nga ilimnon nga bugas' },
      { ko: '수정과', pack: 'Sujeonggwa', say: 'soo-juhng-gwah', en: 'cinnamon ginger punch', bis: 'ilimnon nga cinnamon ug luy-a' },
      { ko: '알로에 음료', pack: 'Aloe Drink', say: 'ahl-loh-eh eum-nyo', en: 'aloe vera drink', bis: 'ilimnon nga aloe vera' },
      { ko: '바나나우유', pack: 'Banana Milk', say: 'bah-nah-nah-oo-yoo', en: 'banana milk (very popular)', bis: 'gatas nga saging (sikat kaayo)' },
      { ko: '보리차', pack: 'Boricha', say: 'boh-ree-chah', en: 'barley tea', bis: 'tsa nga barley' },
      { ko: '옥수수차', pack: 'Oksusucha', say: 'ohk-ssoo-soo-chah', en: 'corn tea', bis: 'tsa nga mais' },
      { ko: '유자차', pack: 'Yujacha', say: 'yoo-jah-chah', en: 'citron honey tea', bis: 'tsa nga citron ug dugos' },
      { ko: '커피믹스', pack: 'Coffee Mix', say: 'kuh-pee-meek-sseu', en: 'instant coffee sticks', bis: 'instant coffee nga stick' },
    ] },
    { id: 'grains', title: 'Rice, Grains & Powders', icon: '🌾', items: [
      { ko: '쌀', pack: 'Ssal', say: 'ssahl', en: 'rice (uncooked)', bis: 'bugas', note: 'Customers ask: 쌀 어디 있어요?' },
      { ko: '찹쌀', pack: 'Chapssal', say: 'chahp-ssahl', en: 'sticky rice', bis: 'pilit nga bugas' },
      { ko: '현미', pack: 'Hyeonmi', say: 'hyun-mee', en: 'brown rice', bis: 'brown rice' },
      { ko: '보리', pack: 'Bori', say: 'boh-ree', en: 'barley', bis: 'barley' },
      { ko: '미숫가루', pack: 'Misugaru', say: 'mee-soot-kkah-roo', en: 'roasted grain powder drink', bis: 'pulbos nga sinanag nga lugas, ilimnon' },
      { ko: '부침가루', pack: 'Buchim Mix', say: 'boo-cheem-gah-roo', en: 'Korean pancake mix', bis: 'harina para sa Korean pancake' },
      { ko: '튀김가루', pack: 'Twigim Mix', say: 'twee-geem-gah-roo', en: 'frying batter mix', bis: 'harina para sa prito' },
      { ko: '밀가루', pack: 'Milgaru', say: 'meel-kkah-roo', en: 'wheat flour', bis: 'harina' },
      { ko: '콩', pack: 'Kong', say: 'kohng', en: 'beans / soybeans', bis: 'liso sa soybean' },
      { ko: '팥', pack: 'Pat', say: 'paht', en: 'red beans', bis: 'pula nga liso, monggos style' },
      { ko: '누룽지', pack: 'Nurungji', say: 'noo-roong-jee', en: 'crispy scorched rice', bis: 'dukot nga bugas, crispy' },
    ] },
    { id: 'household', title: 'Household & Others', icon: '🧴', items: [
      { ko: '수세미', pack: 'Susemi', say: 'soo-seh-mee', en: 'dish scrubber', bis: 'panghugas og plato' },
      { ko: '고무장갑', pack: 'Rubber Gloves', say: 'goh-moo-jahng-gahp', en: 'rubber gloves (the pink ones)', bis: 'rubber gloves nga pink' },
      { ko: '젓가락', pack: 'Jeotgarak', say: 'juht-kkah-rahk', en: 'chopsticks', bis: 'chopsticks' },
      { ko: '숟가락', pack: 'Sutgarak', say: 'soot-kkah-rahk', en: 'spoon', bis: 'kutsara' },
      { ko: '도시락', pack: 'Dosirak', say: 'doh-shee-rahk', en: 'lunch box', bis: 'baon box' },
      { ko: '밥솥', pack: 'Rice Cooker', say: 'bahp-ssoht', en: 'rice cooker', bis: 'rice cooker' },
      { ko: '비누', pack: 'Binu', say: 'bee-noo', en: 'soap', bis: 'sabon' },
      { ko: '치약', pack: 'Chiyak', say: 'chee-yahk', en: 'toothpaste', bis: 'toothpaste' },
      { ko: '휴지', pack: 'Hyuji', say: 'hyoo-jee', en: 'tissue / toilet paper', bis: 'tisyu' },
      { ko: '봉투', pack: 'Bongtu', say: 'bohng-too', en: 'plastic bag', bis: 'plastik nga bag' },
      { ko: '컵', pack: 'Keop', say: 'kuhp', en: 'cup', bis: 'baso' },
    ] },
  ],

  hangul: [
    { id: 'stage1', title: 'Step 1 — Basic letters: read 라면!',
      intro_en: 'Hangul letters stack into blocks. 라 = ㄹ(r) + ㅏ(ah). Learn these first letters and you can already read many products.',
      intro_bis: 'Ang Hangul letra mag-stack og blocks. 라 = ㄹ(r) + ㅏ(ah). Kabaloa ni ug makabasa na ka og daghang produkto.',
      items: [
        { ko: 'ㄱ', say: 'g / k', en: 'like g in "go"', bis: 'sama sa g sa "gatas"' },
        { ko: 'ㄴ', say: 'n', en: 'like n in "no"', bis: 'sama sa n sa "nindot"' },
        { ko: 'ㄷ', say: 'd / t', en: 'like d in "dog"', bis: 'sama sa d sa "dako"' },
        { ko: 'ㄹ', say: 'r / l', en: 'between r and l', bis: 'tunga-tunga sa r ug l' },
        { ko: 'ㅁ', say: 'm', en: 'like m in "mom"', bis: 'sama sa m sa "mama"' },
        { ko: 'ㅂ', say: 'b / p', en: 'like b in "boy"', bis: 'sama sa b sa "bata"' },
        { ko: 'ㅅ', say: 's', en: 'like s in "sun"', bis: 'sama sa s sa "sud-an"' },
        { ko: 'ㅇ', say: '(silent) / ng', en: 'silent at the start, "ng" at the end', bis: 'walay tingog sa sugod, "ng" sa katapusan' },
        { ko: 'ㅈ', say: 'j', en: 'like j in "jam"', bis: 'sama sa j sa "jam"' },
        { ko: 'ㅎ', say: 'h', en: 'like h in "hi"', bis: 'sama sa h sa "hangin"' },
        { ko: 'ㅏ', say: 'ah', en: 'like a in "father"', bis: 'sama sa "a" sa Binisaya' },
        { ko: 'ㅓ', say: 'uh', en: 'like u in "up"', bis: 'sama sa "u" sa English nga "up"' },
        { ko: 'ㅗ', say: 'oh', en: 'like o in "go"', bis: 'sama sa "o" sa Binisaya' },
        { ko: 'ㅜ', say: 'oo', en: 'like oo in "moon"', bis: 'sama sa "u" sa Binisaya' },
        { ko: 'ㅡ', say: 'eu', en: 'oo with flat lips', bis: '"u" pero flat ang ngabil' },
        { ko: 'ㅣ', say: 'ee', en: 'like ee in "see"', bis: 'sama sa "i" sa Binisaya' },
        { ko: '오이', say: 'oh-ee', en: 'cucumber — you can read this now!', bis: 'pipino — mabasa na nimo ni!' },
        { ko: '만두', say: 'mahn-doo', en: 'dumpling — ㅁㅏㄴ + ㄷㅜ', bis: 'dumpling — ㅁㅏㄴ + ㄷㅜ' },
      ] },
    { id: 'stage2', title: 'Step 2 — More letters & how blocks work',
      intro_en: 'Strong (ㄲㄸㅃㅆㅉ), breathy (ㅋㅌㅍㅊ), and y-vowels (ㅑㅕㅛㅠ, ㅐㅔ). Blocks read left→right, top→bottom.',
      intro_bis: 'Kusgan (ㄲㄸㅃㅆㅉ), naay hangin (ㅋㅌㅍㅊ), ug y-vowels (ㅑㅕㅛㅠ, ㅐㅔ). Basaha ang blocks wala→tuo, taas→ubos.',
      items: [
        { ko: 'ㅋ', say: 'k', en: 'k with a puff of air', bis: 'k nga naay hangin' },
        { ko: 'ㅌ', say: 't', en: 't with a puff of air', bis: 't nga naay hangin' },
        { ko: 'ㅍ', say: 'p', en: 'p with a puff of air', bis: 'p nga naay hangin' },
        { ko: 'ㅊ', say: 'ch', en: 'like ch in "chair"', bis: 'sama sa ch sa "chair"' },
        { ko: 'ㄲ', say: 'kk', en: 'hard k, no air', bis: 'kusgan nga k, walay hangin' },
        { ko: 'ㄸ', say: 'tt', en: 'hard t, no air', bis: 'kusgan nga t, walay hangin' },
        { ko: 'ㅃ', say: 'pp', en: 'hard p, no air', bis: 'kusgan nga p, walay hangin' },
        { ko: 'ㅆ', say: 'ss', en: 'hard s', bis: 'kusgan nga s' },
        { ko: 'ㅉ', say: 'jj', en: 'hard j', bis: 'kusgan nga j' },
        { ko: 'ㅑ', say: 'yah', en: 'ya', bis: 'ya' },
        { ko: 'ㅕ', say: 'yuh', en: 'y + uh', bis: 'y + uh' },
        { ko: 'ㅛ', say: 'yoh', en: 'yo', bis: 'yo' },
        { ko: 'ㅠ', say: 'yoo', en: 'yu', bis: 'yu' },
        { ko: 'ㅐ', say: 'eh', en: 'like e in "bed"', bis: 'sama sa "e" sa Binisaya' },
        { ko: 'ㅔ', say: 'eh', en: 'same sound as ㅐ', bis: 'pareha ra sa ㅐ' },
        { ko: '커피', say: 'kuh-pee', en: 'coffee — ㅋㅓ + ㅍㅣ', bis: 'kape — ㅋㅓ + ㅍㅣ' },
        { ko: '차', say: 'chah', en: 'tea — ㅊ + ㅏ', bis: 'tsa — ㅊ + ㅏ' },
      ] },
    { id: 'stage3', title: 'Step 3 — Final sounds (받침)',
      intro_en: 'A letter under the block is the final sound: 김 = ㄱㅣ + ㅁ = "geem". Final sounds are short and closed.',
      intro_bis: 'Ang letra sa ubos sa block mao ang final sound: 김 = ㄱㅣ + ㅁ = "geem". Mubo ug sirado ang final sounds.',
      items: [
        { ko: 'ㄱ (받침)', say: 'k', en: 'final k — stop the sound: 떡 = ttuhk', bis: 'final k — putla ang tingog: 떡 = ttuhk' },
        { ko: 'ㄴ (받침)', say: 'n', en: 'final n: 라면 = rah-myun', bis: 'final n: 라면 = rah-myun' },
        { ko: 'ㄹ (받침)', say: 'l', en: 'final l: 물 = mool', bis: 'final l: 물 = mool' },
        { ko: 'ㅁ (받침)', say: 'm', en: 'final m: 김 = geem', bis: 'final m: 김 = geem' },
        { ko: 'ㅂ (받침)', say: 'p', en: 'final p: 밥 = bahp', bis: 'final p: 밥 = bahp' },
        { ko: 'ㅇ (받침)', say: 'ng', en: 'final ng: 콩 = kohng', bis: 'final ng: 콩 = kohng' },
        { ko: 'ㅅ/ㄷ/ㅌ (받침)', say: 't', en: 'these all sound like a short t at the end', bis: 'tanan ni murag mubo nga t sa katapusan' },
        { ko: '김밥', say: 'geem-bahp', en: 'seaweed rice roll — read it!', bis: 'seaweed rice roll — basaha!' },
        { ko: '물', say: 'mool', en: 'water', bis: 'tubig' },
        { ko: '밥', say: 'bahp', en: 'cooked rice', bis: 'kan-on' },
      ] },
    { id: 'stage4', title: 'Step 4 — Store label words',
      intro_en: 'These words are printed on packages and shelf tags. Learn to spot them fast.',
      intro_bis: 'Kini nga mga pulong naka-print sa mga package ug shelf tags. Kabaloa ni dayon.',
      items: [
        { ko: '매운맛', say: 'meh-oon-maht', en: 'spicy flavor', bis: 'halang' },
        { ko: '순한맛', say: 'soon-hahn-maht', en: 'mild flavor', bis: 'dili halang' },
        { ko: '냉동', say: 'nehng-dohng', en: 'frozen', bis: 'frozen' },
        { ko: '냉장', say: 'nehng-jahng', en: 'refrigerated', bis: 'gibutang sa ref' },
        { ko: '유통기한', say: 'yoo-tohng-gee-hahn', en: 'expiry date', bis: 'expiration date' },
        { ko: '세일', say: 'seh-eel', en: 'sale', bis: 'sale' },
        { ko: '신상품', say: 'sheen-sahng-poom', en: 'new item', bis: 'bag-o nga produkto' },
        { ko: '증정', say: 'jeung-juhng', en: 'free gift included', bis: 'naay libre' },
        { ko: '할인', say: 'hah-reen', en: 'discount', bis: 'diskwento' },
        { ko: '소', say: 'soh', en: 'small (size)', bis: 'gamay' },
        { ko: '중', say: 'joong', en: 'medium (size)', bis: 'medium' },
        { ko: '대', say: 'deh', en: 'large (size)', bis: 'dako' },
      ] },
  ],
};

if (typeof module !== 'undefined') module.exports = APP_DATA;
